#ifndef BASIC_ERR_DEFINITION_H_
#define BASIC_ERR_DEFINITION_H_

#include <cstddef>
#include <ostream>
#include <iostream>
#include <string>
#include <cstdint>

#ifndef BASIC_ERR_CHAR_TYPE
#define BASIC_ERR_CHAR_TYPE char
#endif //!BASIC_ERR_CHAR_TYPE

#ifndef BASIC_ERR_CODE_VALUE_TYPE
#define BASIC_ERR_CODE_VALUE_TYPE std::uint16_t
#endif //!BASIC_ERR_CODE_VALUE_TYPE

#ifndef BASIC_ERR_SYS_CODE_VALUE_TYPE
#define BASIC_ERR_SYS_CODE_VALUE_TYPE std::uint16_t
#endif //!BASIC_ERR_SYS_CODE_VALUE_TYPE

#ifndef BASIC_ERR_SYS_COND_VALUE_TYPE
#define BASIC_ERR_SYS_COND_VALUE_TYPE std::uint16_t
#endif //!BASIC_ERR_SYS_COND_VALUE_TYPE

#ifndef BASIC_ERR_SYS_CATEG_VALUE_TYPE
#define BASIC_ERR_SYS_CATEG_VALUE_TYPE std::uint8_t
#endif //!BASIC_ERR_SYS_CATEG_VALUE_TYPE

#ifndef BASIC_ERR_OUTPUT_CHARTRAIT_TYPE
#define BASIC_ERR_OUTPUT_CHARTRAIT_TYPE\
    std::char_traits<BASIC_ERR_CHAR_TYPE>
#endif //!BASIC_ERR_OUTPUT_CHARTRAIT_TYPE

#ifndef BASIC_ERR_OUTPUT_TYPE
#define BASIC_ERR_OUTPUT_TYPE\
    std::basic_ostream<BASIC_ERR_CHAR_TYPE,\
        BASIC_ERR_OUTPUT_CHARTRAIT_TYPE>
#endif //!BASIC_ERR_OUTPUT_TYPE

#ifndef BASIC_ERR_OUTPUT_VALUE_TYPE
#define BASIC_ERR_OUTPUT_VALUE_TYPE std::size_t
#endif //BASIC_ERR_OUTPUT_VALUE_TYPE

#ifndef BASIC_ERR_ID_RECORD_TYPE
#include "id/Record.h"
#define BASIC_ERR_ID_RECORD_TYPE \
    basic::err::id::Record<BASIC_ERR_CODE_VALUE_TYPE,\
        BASIC_ERR_SYS_CATEG_VALUE_TYPE,\
        BASIC_ERR_SYS_CODE_VALUE_TYPE>
#endif //!BASIC_ERR_IDENTIFICATION_RECORD_TYPE

#ifndef BASIC_ERR_OUTPUT
#define BASIC_ERR_OUTPUT std::cerr
#endif //!BASIC_ERR_OUTPUT

#ifndef BASIC_ERR_OUTPUT_OPERATOR
#define BASIC_ERR_OUTPUT_OPERATOR(OUTPUT_NAME, ARG,...)\
    OUTPUT_NAME << ARG,##__VA_ARGS__
#endif //!BASIC_ERR_OUTPUT_OPERATOR

#ifndef BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC_SIZE
#define BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC_SIZE 256
#endif //!BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC_SIZE

#ifdef USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC
#ifndef BASIC_ERR_MSG_STR_STORAGE_TYPE
#define BASIC_ERR_MSG_STR_STORAGE_TYPE\
    BASIC_ERR_CHAR_TYPE[BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC_SIZE]
#endif //!BASIC_ERR_MSG_STR_STORAGE_TYPE
#endif //!USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC

#ifdef USING_BASIC_ERR_MSG_STR_STORAGE_DYNAMIC
#ifdef USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC
#error "error USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC is defined"
#endif //!USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC
#ifndef BASIC_ERR_MSG_STR_STORAGE_TYPE
#define BASIC_ERR_MSG_STR_STORAGE_TYPE BASIC_ERR_CHAR_TYPE *
#endif //!BASIC_ERR_MSG_STR_STORAGE_TYPE
#endif //!USING_BASIC_ERR_MSG_STR_STORAGE_DYNAMIC

#ifndef USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC
#ifndef USING_BASIC_ERR_MSG_STR_STORAGE_DYNAMIC
#ifndef BASIC_ERR_MSG_STR_STORAGE_TYPE
#define USING_BASIC_ERR_MSG_STR_STORAGE_DYNAMIC
#define BASIC_ERR_MSG_STR_STORAGE_TYPE BASIC_ERR_CHAR_TYPE *
#endif //!BASIC_ERR_MSG_STR_STORAGE_TYPE
#endif //!USING_BASIC_ERR_MSG_STR_STORAGE_DYNAMIC
#endif //!USING_BASIC_ERR_MSG_STR_STORAGE_AUTOMATIC

#endif //!BASIC_ERR_DEFINITION_H_