#ifndef BASIC_MACRO_CONDITIONAL_H_
#define BASIC_MACRO_CONDITIONAL_H_

#define __DEFINE_CONDITIONAL_T_NAME_TRUE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
__T_TRUE_NAME__

#define __DEFINE_CONDITIONAL_T_NAME_FALSE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
__T_FALSE_NAME__

#define __DEFINE_CONDITIONAL_TMPL_PARAM_LIST_TRUE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
typename __T_TRUE_NAME__, typename __T_FALSE_NAME__

#define __DEFINE_CONDITIONAL_TMPL_PARAM_LIST_FALSE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
typename __T_TRUE_NAME__, typename __T_FALSE_NAME__

#define __DEFINE_CONDITIONAL_TMPL_ARG_LIST_FALSE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
__T_TRUE_NAME__, __T_FALSE_NAME__

#define __DEFINE_CONDITIONAL_TMPL_PARAM_TRUE_(\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__TMPL_PARAM_LIST_TRUE_POSTFIX__)\
bool __BOOL_CONDITIONAL_NAME__,\
__DEFINE_CONDITIONAL_TMPL_PARAM_LIST_TRUE_##__TMPL_PARAM_LIST_TRUE_POSTFIX__(\
	__T_TRUE_NAME__, __T_FALSE_NAME__)

#define __DEFINE_CONDITIONAL_TMPL_PARAM_FALSE_(\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__TMPL_PARAM_LIST_FALSE_POSTFIX__)\
__DEFINE_CONDITIONAL_TMPL_PARAM_LIST_FALSE_##__TMPL_PARAM_LIST_FALSE_POSTFIX__(\
	__T_TRUE_NAME__, __T_FALSE_NAME__)

#define __DEFINE_CONDITIONAL_TMPL_ARG_TRUE_(...)

#define __DEFINE_CONDITIONAL_TMPL_ARG_FALSE_(\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__TMPL_ARG_LIST_FALSE_POSTFIX__)\
<false, __DEFINE_CONDITIONAL_TMPL_ARG_LIST_FALSE_\
	##__TMPL_ARG_LIST_FALSE_POSTFIX__(__T_TRUE_NAME__, __T_FALSE_NAME__)>

#define __DEFINE_CONDITIONAL_T_TRUE_DEFN_TYPE_PREFIX_()

#define __DEFINE_CONDITIONAL_T_FALSE_DEFN_TYPE_PREFIX_()

#define __DEFINE_CONDITIONAL_T_TRUE_DEFN_TYPE_MMBR_PREFIX_()\
typename

#define __DEFINE_CONDITIONAL_T_FALSE_DEFN_TYPE_MMBR_PREFIX_()\
__DEFINE_CONDITIONAL_T_TRUE_DEFN_TYPE_MMBR_PREFIX_()

#define __DEFINE_CONDITIONAL_T_TRUE_NAME_(\
	__T__TRUE_OR_FALSE__NAME__, ...)\
__T__TRUE_OR_FALSE__NAME__

#define __DEFINE_CONDITIONAL_T_FALSE_NAME_(\
	__T__TRUE_OR_FALSE__NAME__, ...)\
__DEFINE_CONDITIONAL_T_TRUE_NAME_(__T__TRUE_OR_FALSE__NAME__)

#define __DEFINE_CONDITIONAL_T_TRUE_NAME_TMPL_(\
	__T_TRUE_NAME__,\
	__T_TRUE_NAME_TMPL_ARG_LIST_POSTFIX__)\
__T_TRUE_NAME__<__DEFINE_CONDITIONAL_T_TRUE_NAME_TMPL_ARG_LIST_\
	##__T_TRUE_NAME_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_CONDITIONAL_T_FALSE_NAME_TMPL_(\
	__T_FALSE_NAME__,\
	__T_FALSE_NAME_TMPL_ARG_LIST_POSTFIX__)\
__T_FALSE_NAME__<__DEFINE_CONDITIONAL_T_FALSE_NAME_TMPL_ARG_LIST_\
	##__T_FALSE_NAME_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_CONDITIONAL_T_TRUE_DEFN_TYPE_(...)

#define __DEFINE_CONDITIONAL_T_FALSE_DEFN_TYPE_(...)

#define __DEFINE_CONDITIONAL_T_TRUE_DEFN_TYPE_MMBR_(\
	__T_TRUE_DEFN_MMBR_NAME_POSTFIX__)\
::__DEFINE_CONDITIONAL_T_TRUE_DEFN_MMBR_NAME_\
	##__T_TRUE_DEFN_MMBR_NAME_POSTFIX__()

#define __DEFINE_CONDITIONAL_T_FALSE_DEFN_TYPE_MMBR_(\
	__T_FALSE_DEFN_MMBR_NAME_POSTFIX__)\
::__DEFINE_CONDITIONAL_T_FALSE_DEFN_MMBR_NAME_\
	##__T_FALSE_DEFN_MMBR_NAME_POSTFIX__()

#define __DEFINE_CONDITIONAL_ALIAS_TYPE_TRUE_(\
	__ALIAS_TYPE_NAME__,\
	__TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)\
using __ALIAS_TYPE_NAME__ =\
	__DEFINE_CONDITIONAL_##__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__\
		##PREFIX_()\
	__DEFINE_CONDITIONAL_##__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__(\
		__T__TRUE_OR_FALSE__NAME__,\
		__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__)\
	__DEFINE_CONDITIONAL_\
		##__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__(\
		__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__)
	
#define __DEFINE_CONDITIONAL_ALIAS_TYPE_FALSE_(\
	__ALIAS_TYPE_NAME__,\
	__TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)\
__DEFINE_CONDITIONAL_ALIAS_TYPE_TRUE_(__ALIAS_TYPE_NAME__, __TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__, __T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)

#define __DEFINE_CONDITIONAL_ALIAS_TYPE_TMPL_TRUE_(\
	__ALIAS_TYPE_NAME__,\
	__TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)\
template<__DEFINE_CONDITIONAL_ALIAS_TYPE_TMPL_PARAM_LIST_##__TRUE_OR_FALSE__\
	##__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__()>\
__DEFINE_CONDITIONAL_ALIAS_TYPE_TRUE_(__ALIAS_TYPE_NAME__, __TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__, __T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,)

#define __DEFINE_CONDITIONAL_ALIAS_TYPE_TMPL_FALSE_(\
	__ALIAS_TYPE_NAME__,\
	__TRUE_OR_FALSE__,\
	__T__TRUE_OR_FALSE__NAME__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)\
__DEFINE_CONDITIONAL_ALIAS_TYPE_TMPL_TRUE_(__ALIAS_TYPE_NAME__,\
	__TRUE_OR_FALSE__, __T__TRUE_OR_FALSE__NAME__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)

#define __DEFINE_CONDITIONAL_STRUCT_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__TRUE_OR_FALSE__,\
	__TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__,\
	__TMPL_ARG_LIST_FALSE_POSTFIX__,\
	__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
	__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
	__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__TRUE_OR_FALSE__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)\
template<__DEFINE_CONDITIONAL_TMPL_PARAM_##__TRUE_OR_FALSE__(\
	__BOOL_CONDITIONAL_NAME__, __T_TRUE_NAME__, __T_FALSE_NAME__,\
	__TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__)>\
struct __STRUCT_NAME__ __DEFINE_CONDITIONAL_TMPL_ARG_##__TRUE_OR_FALSE__(\
	__T_TRUE_NAME__, __T_FALSE_NAME__, __TMPL_ARG_LIST_FALSE_POSTFIX__)\
{\
	__DEFINE_CONDITIONAL_\
		##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__TRUE_OR_FALSE__(type,\
			__TRUE_OR_FALSE__, __DEFINE_CONDITIONAL_T_NAME_\
				##__TRUE_OR_FALSE__(__T_TRUE_NAME__, __T_FALSE_NAME__),\
			__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
			__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
			__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
			__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
			__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__);\
	__DEFINE_CONDITIONAL_\
		##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__TRUE_OR_FALSE__(Type,\
			__TRUE_OR_FALSE__, __DEFINE_CONDITIONAL_T_NAME_\
				##__TRUE_OR_FALSE__(__T_TRUE_NAME__, __T_FALSE_NAME__),\
			__T__TRUE_OR_FALSE__NAME_OR_NAME_TMPL__,\
			__T__TRUE_OR_FALSE__NAME_TMPL_ARG_LIST_POSTFIX__,\
			__T__TRUE_OR_FALSE__DEFN_TYPE_OR_DEFN_TYPE_MMBR__,\
			__T__TRUE_OR_FALSE__DEFN_MMBR_NAME_POSTFIX__,\
			__ALIAS_TYPE_TMPL_PARAM_LIST__TRUE_OR_FALSE__POSTFIX__);\
}

#define __DEFINE_CONDITIONAL_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__TMPL_PARAM_LIST_TRUE_POSTFIX__,\
	__T_TRUE_NAME_OR_T_TRUE_NAME_TMPL__,\
	__T_TRUE_NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T_TRUE_DEFN_TYPE_OR_T_TRUE_DEFN_TYPE_MMBR__,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TRUE_OR_ALIAS_TYPE_TMPL_TRUE__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST_TRUE_POSTFIX__,\
	__TMPL_PARAM_LIST_FALSE_POSTFIX__,\
	__TMPL_ARG_LIST_FALSE_POSTFIX__,\
	__T_FALSE_NAME_OR_T_FALSE_NAME_TMPL__,\
	__T_FALSE_NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T_FALSE_DEFN_TYPE_OR_T_FALSE_DEFN_TYPE_MMBR__,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_FALSE_OR_ALIAS_TYPE_TMPL_FALSE__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST_FALSE_POSTFIX__)\
__DEFINE_CONDITIONAL_STRUCT_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__, TRUE_,\
	__TMPL_PARAM_LIST_TRUE_POSTFIX__,, __T_TRUE_NAME_OR_T_TRUE_NAME_TMPL__,\
	__T_TRUE_NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T_TRUE_DEFN_TYPE_OR_T_TRUE_DEFN_TYPE_MMBR__,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_TRUE_OR_ALIAS_TYPE_TMPL_TRUE__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST_TRUE_POSTFIX__);\
__DEFINE_CONDITIONAL_STRUCT_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__, FALSE_,\
	__TMPL_PARAM_LIST_FALSE_POSTFIX__, __TMPL_ARG_LIST_FALSE_POSTFIX__,\
	__T_FALSE_NAME_OR_T_FALSE_NAME_TMPL__,\
	__T_FALSE_NAME_TMPL_ARG_LIST_POSTFIX__,\
	__T_FALSE_DEFN_TYPE_OR_T_FALSE_DEFN_TYPE_MMBR__,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__,\
	__ALIAS_TYPE_FALSE_OR_ALIAS_TYPE_TMPL_FALSE__,\
	__ALIAS_TYPE_TMPL_PARAM_LIST_FALSE_POSTFIX__)

#define __DEFINE_CONDITIONAL_DEFAULT_TRUE_FALSE_TYPE_DEFN_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__)\
__DEFINE_CONDITIONAL_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__,, T_TRUE_NAME_,, T_TRUE_DEFN_TYPE_,,\
	ALIAS_TYPE_TRUE_,,,, T_FALSE_NAME_,, T_FALSE_DEFN_TYPE_,,\
	ALIAS_TYPE_FALSE_,)

#define __DEFINE_CONDITIONAL_DEFAULT_TRUE_TYPE_DEFN_FALSE_TYPE_MMBR_DEFN_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__)\
__DEFINE_CONDITIONAL_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__,, T_TRUE_NAME_,, T_TRUE_DEFN_TYPE_,,\
	ALIAS_TYPE_TRUE_,,,, T_FALSE_NAME_,, T_FALSE_DEFN_TYPE_MMBR_,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__, ALIAS_TYPE_FALSE_,)

#define __DEFINE_CONDITIONAL_DEFAULT_TRUE_TYPE_MMBR_DEFN_FALSE_TYPE_DEFN_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__)\
__DEFINE_CONDITIONAL_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__,, T_TRUE_NAME_,, T_TRUE_DEFN_TYPE_MMBR_,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__, ALIAS_TYPE_TRUE_,,,,\
	T_FALSE_NAME_,, T_FALSE_DEFN_TYPE_,, ALIAS_TYPE_FALSE_,)

#define __DEFINE_CONDITIONAL_DEFAULT_TRUE_FALSE_TYPE_MMBR_DEFN_(\
	__STRUCT_NAME__,\
	__BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__,\
	__T_FALSE_NAME__,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__)\
__DEFINE_CONDITIONAL_(__STRUCT_NAME__, __BOOL_CONDITIONAL_NAME__,\
	__T_TRUE_NAME__, __T_FALSE_NAME__,, T_TRUE_NAME_,, T_TRUE_DEFN_TYPE_MMBR_,\
	__T_TRUE_DEFN_TYPE_MMBR_NAME_POSTFIX__, ALIAS_TYPE_TRUE_,,,,\
	T_FALSE_NAME_,, T_FALSE_DEFN_TYPE_MMBR_,\
	__T_FALSE_DEFN_TYPE_MMBR_NAME_POSTFIX__, ALIAS_TYPE_FALSE_,)

#endif //!BASIC_MACRO_CONDITIONAL_H_
