#ifndef BASIC_MACRO_ENABLEIF_H_
#define BASIC_MACRO_ENABLEIF_H_

#define __DEFINE_ENABLE_IF_TMPL_PARAM_LIST_PRIMARY_(\
    __T_NAME__,\
    __T_OUT_NAME__)\
typename __T_NAME__, typename __T_OUT_NAME__ = void

#define __DEFINE_ENABLE_IF_TMPL_PARAM_LIST_SPECIALIZED_(\
    __T_NAME__,\
    __T_OUT_NAME__)\
typename __T_NAME__, typename __T_OUT_NAME__

#define __DEFINE_ENABLE_IF_TMPL_PARAM_PRIMARY_(\
    __BOOL_TEST_NAME__,\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
    __CONDITIONAL__, ...)\
bool __BOOL_TEST_NAME__, __DEFINE_ENABLE_IF_TMPL_PARAM_LIST_PRIMARY_\
    ##__TMPL_PARAM_LIST_PRIMARY_POSTFIX__(__T_NAME__, __T_OUT_NAME__),\
        bool = __CONDITIONAL__,##__VA_ARGS__

#define __DEFINE_ENABLE_IF_TMPL_PARAM_SPECIALIZED_(\
    __BOOL_TEST_NAME__,\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
    __CONDITIONAL__, ...)\
__DEFINE_ENABLE_IF_TMPL_PARAM_LIST_SPECIALIZED_\
    ##__TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__(__T_NAME__, __T_OUT_NAME__)

#define __DEFINE_ENABLE_IF_TMPL_ARG_LIST_(\
    __T_NAME__,\
    __T_OUT_NAME__)\
__T_NAME__, __T_OUT_NAME__

#define __DEFINE_ENABLE_IF_TMPL_ARG_LIST_PRIMARY_(...)

#define __DEFINE_ENABLE_IF_TMPL_ARG_LIST_SPECIALIZED_(\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __TEST_BOOL__,\
    __CONDITIONAL_BOOL__,\
    __TMPL_ARG_LIST_POSTFIX__)\
<__TEST_BOOL__, __DEFINE_ENABLE_IF_TMPL_ARG_LIST_\
    ##__TMPL_ARG_LIST_POSTFIX__(__T_NAME__, __T_OUT_NAME__),\
        __CONDITIONAL_BOOL__>

#define __DEFINE_ENABLE_IF_ALIAS_TYPE_PRIMARY_(\
    __ALIAS_TYPE_NAME__,\
    __T_OUT_NAME__, ...)\
using __ALIAS_TYPE_NAME__ = __T_OUT_NAME__

#define __DEFINE_ENABLE_IF_ALIAS_TYPE_TMPL_PRIMARY_(\
    __ALIAS_TYPE_NAME__,\
    __T_OUT_NAME__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__)\
template<__DEFINE_ENABLE_IF_ALIAS_TYPE_TMPL_PARAM_LIST_\
    ##__ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__()>\
__DEFINE_ENABLE_IF_ALIAS_TYPE_PRIMARY_(__ALIAS_TYPE_NAME__, __T_OUT_NAME__,,,)\
<__DEFINE_ENABLE_IF_ALIAS_TYPE_TMPL_ARG_LIST_\
    ##__ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_ENABLE_IF_ALIAS_TYPE_SPECIALIZED_(...)
#define __DEFINE_ENABLE_IF_ALIAS_TYPE_TMPL_SPECIALIZED_(...)

#define __DEFINE_ENABLE_IF_STRUCT_(\
    __STRUCT_NAME__,\
    __BOOL_TEST_NAME__,\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __TEST_BOOL__,\
    __CONDITIONAL_BOOL__,\
    __PRIMARY_OR_SPECIALIZED__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
    __TMPL_ARG_LIST_POSTFIX__,\
    __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
    __CONDITIONAL__,...)\
template<__DEFINE_ENABLE_IF_TMPL_PARAM_\
    ##__PRIMARY_OR_SPECIALIZED__(__BOOL_TEST_NAME__, __T_NAME__,\
        __T_OUT_NAME__, __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
            __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
                __CONDITIONAL__,##__VA_ARGS__)>\
struct __STRUCT_NAME__ __DEFINE_ENABLE_IF_TMPL_ARG_LIST_\
    ##__PRIMARY_OR_SPECIALIZED__(__T_NAME__, __T_OUT_NAME__,\
        __TEST_BOOL__, __CONDITIONAL_BOOL__, __TMPL_ARG_LIST_POSTFIX__)\
{\
    __DEFINE_ENABLE_IF_##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL\
        ##__PRIMARY_OR_SPECIALIZED__(type, __T_OUT_NAME__,\
            __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__);\
    __DEFINE_ENABLE_IF_##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL\
        ##__PRIMARY_OR_SPECIALIZED__(Type, __T_OUT_NAME__,\
            __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__);\
}

#define __DEFINE_ENABLE_IF_(\
    __STRUCT_NAME__,\
    __BOOL_TEST_NAME__,\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
    __TMPL_ARG_LIST_POSTFIX__,\
    __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
    __CONDITIONAL__, ...)\
__DEFINE_ENABLE_IF_STRUCT_(__STRUCT_NAME__, __BOOL_TEST_NAME__, __T_NAME__,\
    __T_OUT_NAME__,,, PRIMARY_, __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
        __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__, __TMPL_ARG_LIST_POSTFIX__,\
            __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
                __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                    __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
                        __CONDITIONAL__,##__VA_ARGS__);\
__DEFINE_ENABLE_IF_STRUCT_(__STRUCT_NAME__, __BOOL_TEST_NAME__, __T_NAME__,\
    __T_OUT_NAME__, true, false, SPECIALIZED_, \
        __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
            __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
                __TMPL_ARG_LIST_POSTFIX__, __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
                    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                        __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
                            __CONDITIONAL__,##__VA_ARGS__);\
__DEFINE_ENABLE_IF_STRUCT_(__STRUCT_NAME__, __BOOL_TEST_NAME__, __T_NAME__,\
    __T_OUT_NAME__, false, true, SPECIALIZED_, \
        __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
            __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
                __TMPL_ARG_LIST_POSTFIX__, __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
                    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                        __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
                            __CONDITIONAL__,##__VA_ARGS__);\
__DEFINE_ENABLE_IF_STRUCT_(__STRUCT_NAME__, __BOOL_TEST_NAME__, __T_NAME__,\
    __T_OUT_NAME__, false, false, SPECIALIZED_, \
        __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
            __TMPL_PARAM_LIST_SPECIALIZED_POSTFIX__,\
                __TMPL_ARG_LIST_POSTFIX__, __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL,\
                    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
                        __ALIAS_TYPE_TMPL_ARG_LIST_POSTFIX__,\
                            __CONDITIONAL__,##__VA_ARGS__)

#define __DEFINE_ENABLE_IF_DEFAULT_(\
    __STRUCT_NAME__,\
    __BOOL_TEST_NAME__,\
    __T_NAME__,\
    __T_OUT_NAME__,\
    __CONDITIONAL__, ...)\
__DEFINE_ENABLE_IF_(__STRUCT_NAME__, __BOOL_TEST_NAME__, __T_NAME__,\
    __T_OUT_NAME__,,,, ALIAS_TYPE_,,, __CONDITIONAL__,##__VA_ARGS__)

#endif //!BASIC_MACRO_ENABLEIF_H_
