#ifndef MACRO_HASOBJECTMEMBER_H_
#define MACRO_HASOBJECTMEMBER_H_

#include <type_traits>
#include "../type/trait/rem/ptr/Recursive.h"

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TRUE_TMPL_PARAM_LIST_(\
    __T_NAME__)\
typename __T_NAME__

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_T_NAME_(\
    __T_NAME__, ...)\
__T_NAME__

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_T_NAME_TMPL_(\
    __T_NAME__,\
    __PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__)\
__T_NAME__<__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_T_NAME_TMPL_ARG_LIST_\
    ##__PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TRUE_(\
    __PROTO_FUNC_NAME__,\
    __T_NAME__,\
    __PROTO_FUNC_TRUE_TMPL_PARAM_LIST_POSTFIX__,\
    __PROTO_FUNC_T_NAME_OR_PROTO_FUNC_T_NAME_TMPL__,\
    __PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __MMBR_OBJ_NAME__, ...)\
template<__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TRUE_TMPL_PARAM_LIST_\
    ##__PROTO_FUNC_TRUE_TMPL_PARAM_LIST_POSTFIX__(__T_NAME__)>\
constexpr auto __PROTO_FUNC_NAME__(__DEFINE_HAS_MMBR_OBJ_\
    ##__PROTO_FUNC_T_NAME_OR_PROTO_FUNC_T_NAME_TMPL__(__T_NAME__,\
        __PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__) t) ->\
decltype(t.__MMBR_OBJ_NAME__,##__VA_ARGS__, std::true_type())

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_FALSE_TMPL_PARAM_LIST_(\
    __T_NAME__)\
typename __T_NAME__

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_FALSE_(\
    __PROTO_FUNC_NAME__,\
    __T_NAME__,\
    __PROTO_FUNC_FALSE_TMPL_PARAM_LIST_POSTFIX__)\
template<__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_FALSE_TMPL_PARAM_LIST_\
    ##__PROTO_FUNC_FALSE_TMPL_PARAM_LIST_POSTFIX__(__T_NAME__)>\
constexpr std::false_type __PROTO_FUNC_NAME__(...)

#define __DEFINE_HAS_MMBR_OBJ_TMPL_PARAM_LIST_(\
    __T_NAME__)\
typename __T_NAME__

#define __DEFINE_HAS_MMBR_OBJ_ALIAS_VAL_TYPE_(\
    __ALIAS_VAL_TYPE_NAME__)\
typedef bool __ALIAS_VAL_TYPE_NAME__

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_(\
    __PROTO_FUNC_NAME__, ...)\
__PROTO_FUNC_NAME__

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_ARG_LIST_(\
    __T_NAME__,\
    __T_NAME_REM_RECV_PTR_TYPE__)\
__T_NAME_REM_RECV_PTR_TYPE__

#define __DEFINE_HAS_MMBR_OBJ_T_NAME_(\
    __T_NAME__, ...)\
__T_NAME__

#define __DEFINE_HAS_MMBR_OBJ_T_NAME_TMPL_(\
    __T_NAME__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__)\
__T_NAME__<__DEFINE_HAS_MMBR_OBJ_T_NAME_TMPL_ARG_LIST__\
    ##__T_NAME_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_HAS_MMBR_OBJ_T_NAME_REM_RECV_PTR_TYPE_(\
    __T_NAME__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__)\
typename basic::type::trait::rem::ptr::Recursive<__DEFINE_HAS_MMBR_OBJ_\
    ##__T_NAME_OR_T_NAME_TMPL__(__T_NAME__,\
        __T_NAME_TMPL_ARG_LIST_POSTFIX__)>::type

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_(\
    __T_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)\
__PROTO_FUNC_NAME__<__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_ARG_LIST_\
    ##__PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__(__T_NAME__,\
        __DEFINE_HAS_MMBR_OBJ_T_NAME_REM_RECV_PTR_TYPE_(__T_NAME__,\
            __T_NAME_OR_T_NAME_TMPL__, __T_NAME_TMPL_ARG_LIST_POSTFIX__))>

#define __DEFINE_HAS_MMBR_OBJ_T_NAME_DECLVAL_(\
    __T_NAME__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__)\
std::declval<typename std::remove_cv<\
    __DEFINE_HAS_MMBR_OBJ_T_NAME_REM_RECV_PTR_TYPE_(__T_NAME__,\
        __T_NAME_OR_T_NAME_TMPL__, __T_NAME_TMPL_ARG_LIST_POSTFIX__)>::type>()

#define __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_DECLTYPE_(\
    __T_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)\
decltype(__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_(__T_NAME__,\
    __PROTO_FUNC_NAME__, __T_NAME_OR_T_NAME_TMPL__,\
        __T_NAME_TMPL_ARG_LIST_POSTFIX__, __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__\
            )(__DEFINE_HAS_MMBR_OBJ_T_NAME_DECLVAL_(__T_NAME__,\
                __T_NAME_OR_T_NAME_TMPL__, __T_NAME_TMPL_ARG_LIST_POSTFIX__)))

#define __DEFINE_HAS_MMBR_OBJ_VAL_(\
    __VAL_NAME__,\
    __ALIAS_VAL_TYPE_NAME__,\
    __T_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)\
static constexpr __ALIAS_VAL_TYPE_NAME__ __VAL_NAME__ =\
    __DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TMPL_DECLTYPE_(__T_NAME__,\
        __PROTO_FUNC_NAME__, __T_NAME_OR_T_NAME_TMPL__,\
            __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
                __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)::value

#define __DEFINE_HAS_MMBR_OBJ_STRUCT_(\
    __STRUCT_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME__,\
    __TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)\
template<__DEFINE_HAS_MMBR_OBJ_TMPL_PARAM_LIST_\
    ##__TMPL_PARAM_LIST_POSTFIX__(__T_NAME__)>\
struct __STRUCT_NAME__\
{\
    __DEFINE_HAS_MMBR_OBJ_ALIAS_VAL_TYPE_(value_type);\
    __DEFINE_HAS_MMBR_OBJ_ALIAS_VAL_TYPE_(ValueType);\
    __DEFINE_HAS_MMBR_OBJ_VAL_(value, value_type, __T_NAME__,\
        __PROTO_FUNC_NAME__, __T_NAME_OR_T_NAME_TMPL__,\
            __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
                __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__);\
    __DEFINE_HAS_MMBR_OBJ_VAL_(Value, ValueType, __T_NAME__,\
        __PROTO_FUNC_NAME__, __T_NAME_OR_T_NAME_TMPL__,\
            __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
                __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__);\
}

#define __DEFINE_HAS_MMBR_OBJ_(\
    __STRUCT_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME__,\
    __TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__,\
    __PROTO_FUNC_TRUE_TMPL_PARAM_LIST_POSTFIX__,\
    __PROTO_FUNC_FALSE_TMPL_PARAM_LIST_POSTFIX__,\
    __PROTO_FUNC_T_NAME_OR_PROTO_FUNC_T_NAME_TMPL__,\
    __PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __MMBR_OBJ_NAME__, ...)\
__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_TRUE_(__PROTO_FUNC_NAME__, __T_NAME__,\
    __PROTO_FUNC_TRUE_TMPL_PARAM_LIST_POSTFIX__,\
        __PROTO_FUNC_T_NAME_OR_PROTO_FUNC_T_NAME_TMPL__,\
            __PROTO_FUNC_T_NAME_TMPL_ARG_LIST_POSTFIX__,\
                __MMBR_OBJ_NAME__,##__VA_ARGS__);\
__DEFINE_HAS_MMBR_OBJ_PROTO_FUNC_FALSE_(__PROTO_FUNC_NAME__,\
    __T_NAME__, __PROTO_FUNC_FALSE_TMPL_PARAM_LIST_POSTFIX__);\
__DEFINE_HAS_MMBR_OBJ_STRUCT_(__STRUCT_NAME__, __PROTO_FUNC_NAME__,\
    __T_NAME__, __TMPL_PARAM_LIST_POSTFIX__, __T_NAME_OR_T_NAME_TMPL__,\
        __T_NAME_TMPL_ARG_LIST_POSTFIX__, __PROTO_FUNC_TMPL_ARG_LIST_POSTFIX__)

#define __DEFINE_HAS_MMBR_OBJ_DEFAULT_(\
    __STRUCT_NAME__,\
    __PROTO_FUNC_NAME__,\
    __T_NAME__,\
    __MMBR_OBJ_NAME__, ...)\
__DEFINE_HAS_MMBR_OBJ_(__STRUCT_NAME__, __PROTO_FUNC_NAME__, __T_NAME__,,\
    T_NAME_,,,,, PROTO_FUNC_T_NAME_,, __MMBR_OBJ_NAME__,##__VA_ARGS__)

#endif //!MACRO_HASOBJECTMEMBER_H_
