#ifndef BASIC_MACRO_ISSAMEWITH_H_
#define BASIC_MACRO_ISSAMEWITH_H_

#include <type_traits>

#define __DEFINE_IS_SAME_WITH_TMPL_PARAM_LIST_PRIMARY_(__T_NAME__)\
typename __T_NAME__

#define __DEFINE_IS_SAME_WITH_TMPL_PARAM_LIST_SPECIALIZE_(__T_NAME__)\

#define __DEFINE_IS_SAME_WITH_TMPL_PARAM_PRIMARY_(\
    __T_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__)\
__DEFINE_IS_SAME_WITH_TMPL_PARAM_LIST_PRIMARY_\
    ##__TMPL_PARAM_LIST_PRIMARY_POSTFIX__(__T_NAME__)

#define __DEFINE_IS_SAME_WITH_TMPL_PARAM_SPECIALIZE_(\
    __T_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__)\
__DEFINE_IS_SAME_WITH_TMPL_PARAM_LIST_SPECIALIZE_\
    ##__TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__(__T_NAME__)

#define __DEFINE_IS_SAME_WITH_TMPL_ARG_PRIMARY_(...)

#define __DEFINE_IS_SAME_WITH_TMPL_ARG_SPECIALIZE_(\
    __ARG_LIST_SPECIALIZE__, ...)\
<__ARG_LIST_SPECIALIZE__,##__VA_ARGS__>

#define __DEFINE_IS_SAME_WITH_VALUE_PRIMARY_()\
false

#define __DEFINE_IS_SAME_WITH_VALUE_SPECIALIZE_()\
true

#define __DEFINE_IS_SAME_WITH_STRUCT_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __PRIMARY_OR_SPECIALIZE__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__,\
    __ARG_LIST_SPECIALIZE__, ...)\
template<__DEFINE_IS_SAME_WITH_TMPL_PARAM_##__PRIMARY_OR_SPECIALIZE__(\
    __T_NAME__,__TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
        __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__)>\
struct __STRUCT_NAME__ __DEFINE_IS_SAME_WITH_TMPL_ARG_\
    ##__PRIMARY_OR_SPECIALIZE__(__ARG_LIST_SPECIALIZE__,##__VA_ARGS__)\
{\
    typedef bool value_type;\
    typedef bool ValueType;\
    static constexpr value_type value =\
        __DEFINE_IS_SAME_WITH_VALUE_##__PRIMARY_OR_SPECIALIZE__();\
    static constexpr ValueType Value =\
        __DEFINE_IS_SAME_WITH_VALUE_##__PRIMARY_OR_SPECIALIZE__();\
}

#define __DEFINE_IS_SAME_WITH_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
    __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__,\
    __ARG_LIST_SPECIALIZE__, ...)\
__DEFINE_IS_SAME_WITH_STRUCT_(__STRUCT_NAME__, __T_NAME__, PRIMARY_,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
        __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__,\
            __ARG_LIST_SPECIALIZE__,##__VA_ARGS__);\
__DEFINE_IS_SAME_WITH_STRUCT_(__STRUCT_NAME__, __T_NAME__, SPECIALIZE_,\
    __TMPL_PARAM_LIST_PRIMARY_POSTFIX__,\
        __TMPL_PARAM_LIST_SPECIALIZE_POSTFIX__,\
            __ARG_LIST_SPECIALIZE__,##__VA_ARGS__)

#define __DEFINE_IS_SAME_WITH_DEFAULT_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __ARG_LIST_SPECIALIZE__, ...)\
__DEFINE_IS_SAME_WITH_(__STRUCT_NAME__, __T_NAME__,,,\
    __ARG_LIST_SPECIALIZE__,##__VA_ARGS__)

#endif //!BASIC_MACRO_ISSAMEWITH_H_
