#ifndef BASIC_MACRO_MEMBERDEFINITION_H_
#define BASIC_MACRO_MEMBERDEFINITION_H_

#define __DEFINE_MMBR_DEFN_TMPL_PARAM_LIST_(__T_NAME__)\
typename __T_NAME__

#define __DEFINE_MMBR_DEFN_T_NAME_(\
    __T_NAME__, ...)\
__T_NAME__

#define __DEFINE_MMBR_DEFN_T_NAME_TMPL_(\
    __T_NAME_,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__)\
__T_NAME__<__DEFINE_MMBR_DEFN_T_NAME_TMPL_ARG_LIST_\
    ##__T_NAME_TMPL_ARG_LIST_POSTFIX__()>

#define __DEFINE_MMBR_DEFN_ALIAS_TYPE_(\
    __ALIAS_TYPE_NAME__,\
    __T_NAME__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __MMBR_DEFN_NAME__, ...)\
using __ALIAS_TYPE_NAME__ =\
    typename __DEFINE_MMBR_DEFN_##__T_NAME_OR_T_NAME_TMPL__(\
        __T_NAME__, __T_NAME_TMPL_ARG_LIST_POSTFIX__)::\
        __MMBR_DEFN_NAME__,##__VA_ARGS__

#define __DEFINE_MMBR_DEFN_ALIAS_TYPE_TMPL_(\
    __ALIAS_TYPE_NAME__,\
    __T_NAME__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __MMBR_DEFN_NAME__, ...)\
template<__DEFINE_MMBR_DEFN_ALIAS_TYPE_TMPL_PARAM_LIST_\
    ##__ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__()>\
__DEFINE_MMBR_DEFN_ALIAS_TYPE_(__ALIAS_TYPE_NAME__, __T_NAME__,,\
    __T_NAME_OR_T_NAME_TMPL__, __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __MMBR_DEFN_NAME__,##__VA_ARGS__)

#define __DEFINE_MMBR_DEFN_STRUCT_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __MMBR_DEFN_NAME__, ...)\
template<__DEFINE_MMBR_DEFN_TMPL_PARAM_LIST_\
    ##__TMPL_PARAM_LIST_POSTFIX__(__T_NAME__)>\
struct __STRUCT_NAME__\
{\
    __DEFINE_MMBR_DEFN_##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__(type, __T_NAME__,\
        __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__, __T_NAME_OR_T_NAME_TMPL__,\
        __T_NAME_TMPL_ARG_LIST_POSTFIX__, __MMBR_DEFN_NAME__,##__VA_ARGS__);\
    __DEFINE_MMBR_DEFN_##__ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__(Type, __T_NAME__,\
        __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__, __T_NAME_OR_T_NAME_TMPL__,\
        __T_NAME_TMPL_ARG_LIST_POSTFIX__, __MMBR_DEFN_NAME__,##__VA_ARGS__);\
}

#define __DEFINE_MMBR_DEFN_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __TMPL_PARAM_LIST_POSTFIX__,\
    __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__,\
    __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__,\
    __MMBR_DEFN_NAME__, ...)\
__DEFINE_MMBR_DEFN_STRUCT_(__STRUCT_NAME__, __T_NAME__,\
    __TMPL_PARAM_LIST_POSTFIX__, __T_NAME_OR_T_NAME_TMPL__,\
    __T_NAME_TMPL_ARG_LIST_POSTFIX__, __ALIAS_TYPE_OR_ALIAS_TYPE_TMPL__,\
    __ALIAS_TYPE_TMPL_PARAM_LIST_POSTFIX__, __MMBR_DEFN_NAME__,##__VA_ARGS__)

#define __DEFINE_MMBR_DEFN_DEFAULT_(\
    __STRUCT_NAME__,\
    __T_NAME__,\
    __MMBR_DEFN_NAME__, ...)\
__DEFINE_MMBR_DEFN_(__STRUCT_NAME__, __T_NAME__,, T_NAME_,, ALIAS_TYPE_,,\
    __MMBR_DEFN_NAME__,##__VA_ARGS__)

#endif //!BASIC_MACRO_MEMBERDEFINITION_H_
